sudo: required
services:
    - docker

script:
    - docker build -t efisito/node . 
    - docker images efisito/node

before_deploy:
    - docker login -u "efisito" -p "P13rr3_@r0nn4x"

deploy:
    provider: script
    script: docker push efisito/node
    on:
        branch: master